- name: install packages
  apt: name=nginx state=present
  notify: start nginx

- name: remove default config in sites-available
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: remove default config in sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: add main config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: copy site configs
  template: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item }}
  with_items:
    - datachef
    - jenkins
    - locust
  notify: reload nginx
