- name: install packages
  apt: name=nginx state=present
  notify: start nginx

- name: remove default config in sites-available
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: remove default config in sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: add main config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: add datachef config
  template: src=datachef dest=/etc/nginx/sites-enabled/datachef
  notify: reload nginx

- name: add jenkins config
  template: src=jenkins dest=/etc/nginx/sites-enabled/jenkins
  notify: restart nginx
