- name: Create a secondary, non-root user
  user: name={{ NORMAL_USER_NAME }}
        shell=/bin/bash

- name: Add remote authorized key to allow future passwordless logins
  authorized_key: user={{ NORMAL_USER_NAME }} key="{{ lookup('file', '/home/{{ LOCAL_USER_NAME }}/.ssh/id_rsa.pub') }}"

- name: Add normal user to sudoers
  lineinfile: 'dest=/etc/sudoers
              regexp="{{ NORMAL_USER_NAME }} ALL"
              line="{{ NORMAL_USER_NAME }} ALL=(ALL) NOPASSWD: ALL"
              state=present'

- name: Add supervisor sudoers config
  template:
    src: supervisor
    dest: /etc/sudoers.d/supervisor

- name: Add nginx sudoers config
  template:
    src: nginx
    dest: /etc/sudoers.d/nginx

- name: "Add .pgpass file for {{ NORMAL_USER_NAME }}"
  template:
    src: .pgpass
    dest: /home/{{ NORMAL_USER_NAME }}/.pgpass
    mode: 0600

- name: Add .emacs file
  template:
    src: .emacs
    dest: /home/{{ NORMAL_USER_NAME }}/.emacs

- name: Add .emacs file for root
  template:
    src: .emacs
    dest: /root/.emacs
