- name: remove default timezone
  file:
    path: /etc/localtime
    state: absent

- name: set the timezone for the server to be Europe/Amsterdam
  file:
    src: /usr/share/zoneinfo/Europe/Amsterdam
    dest: /etc/localtime
    state: link

- name: set up a unique hostname
  hostname: name={{ LOCAL_HOSTNAME }}

- name: update the apt cache
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: safe
    update_cache: yes

- name: apt remove unused
  apt:
    autoremove: yes

- name: install base requirements
  apt:
    name: [
      'ntp',
      'python3-dev',
      'libjpeg62-dev',
      'libpng-dev',
      'zlib1g-dev',
      'software-properties-common',
      'openjdk-8-jre',
      'build-essential',
      'git',
      'curl',
      'libssl-dev',
      'libreadline-dev',
      'autoconf',
      'bison',
      'libyaml-dev',
      'libreadline-dev',
      'libncurses5-dev',
      'libffi-dev',
      'libgdbm-dev',
      'python3-boto3',
      'virtualenv',
      'emacs-nox',
      'mailutils',
      'pgtop',
      'binutils',
      'libproj-dev',
      'rustc',
    ]
    state: present

- name: start and enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ntp
