- name: install postgres
  apt:
    name: ['postgresql-12', 'postgresql-server-dev-12', 'python3-psycopg2']
    state: present
  notify: start postgres

- name: start and enable postgres server
  service: name=postgresql state=started enabled=yes
