- name: install packages
  apt:
    name: ['certbot', 'python3-certbot-nginx']
    state: present

- name: "create cert for {{ DATACHEF_HOSTNAME }}"
  command: "certbot certonly -n {{ CERTBOT_STAGING_FLAG }} --nginx -m {{ CERTBOT_EMAIL }} -d {{ DATACHEF_HOSTNAME }} --agree-tos"
  args:
    creates: "/etc/letsencrypt/live/{{ DATACHEF_HOSTNAME }}/"

- name: "create cert for {{ JENKINS_HOSTNAME }}"
  command: "certbot certonly -n {{ CERTBOT_STAGING_FLAG }} --nginx -m {{ CERTBOT_EMAIL }} -d {{ JENKINS_HOSTNAME }} --agree-tos"
  args:
    creates: "/etc/letsencrypt/live/{{ JENKINS_HOSTNAME }}/"

- name: "create cert for {{ LOCUST_HOSTNAME }}"
  command: "certbot certonly -n {{ CERTBOT_STAGING_FLAG }} --nginx -m {{ CERTBOT_EMAIL }} -d {{ LOCUST_HOSTNAME }} --agree-tos"
  args:
    creates: "/etc/letsencrypt/live/{{ LOCUST_HOSTNAME }}/"
